# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # Source here https://app.vagrantup.com/ubuntu/boxes/focal64
    config.vm.box = "ubuntu/bionic64"
    # config.vm.boot_timeout = 400

    config.vm.define "base_image"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "test.yml"

    ansible.verbose = "v"
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
    end
  end